apiVersion: v1
kind: Service
metadata:
  name: {{ include "openwebui-ollama.fullname" . }}-ollama
  labels:
    {{- include "openwebui-ollama.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - name: http
      port: {{ .Values.ollama.service.port }}
      targetPort: 11434
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "openwebui-ollama.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ollama