apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openwebui-ollama.fullname" . }}-ollama
  labels:
    {{- include "openwebui-ollama.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  replicas: {{ .Values.ollama.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "openwebui-ollama.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "openwebui-ollama.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ollama
    spec:
      containers:
        - name: ollama
          image: "{{ .Values.ollama.image.repository }}:{{ .Values.ollama.image.tag }}"
          imagePullPolicy: {{ .Values.ollama.image.pullPolicy }}
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: {{ include "openwebui-ollama.fullname" . }}-ollama-data